### ISSUE TITLE
Demo shows nothing

### ISSUE THREAD

**Issue by MediaMaquina** [elrumordelaluz/svgsprit.es#15]
Hi, doesn't seem to work for [my svg](https://upload.wikimedia.org/wikipedia/commons/9/9e/Flag_of_Japan.svg) on latest chrome.

**Comment by elrumordelaluz** [comment]
Hi @MediaMaquina, thanks for open the _Issue_. 
What are you trying and where? Did you try [here](https://svgsprit.es/)?

**Comment by MediaMaquina** [comment]
Hi, I downloaded the svg from the link. Dragged it to the site. Downloaded the resulting demo.html. opened demo with google chrome PC. The svg does not render on the demo.

**Comment by aldaw** [comment]
I am sure it is the same problem as here: https://github.com/elrumordelaluz/svgsprit.es/issues/16
Which SVG did you use? Do you even maybe can look up which svg version it hat?

**Comment by elrumordelaluz** [comment]
Should be fixed now, there was an _issue_ with the `viewBox` from the core package. 


<img width="1552" alt="Screenshot 2020-10-12 at 12 19 49" src="https://user-images.githubusercontent.com/784056/95735618-561f2f00-0c85-11eb-92d5-ea20ea67ee78.png">


Closing, bu feel free to re-open in any case.
