### ISSUE TITLE
NaN in path

### ISSUE THREAD

**Issue by dinoboff** [elrumordelaluz/svgsprit.es#17]
I have an issue with ionicons lock:
https://unpkg.com/ionicons@5.2.3/dist/svg/lock-closed-outline.svg

_svgspirt.es_ converts it to:

    <svg width="0" height="0" class="hidden">
      <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" id="lock-closed-outline">
        <title>Lock Closed</title>
        <path d="M336 208v-95a80 80 0 0-160 0 NaN" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32"></path>
        <rect x="96" y="208" width="320" height="272" rx="48" ry="48" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32"></rect>
      </symbol>
    </svg>`

_svgspirt.es_ is struggling with the path: 

`<path d='M336 208v-95a80 80 0 00-160 0v95'> </path>` => `<path d="M336 208v-95a80 80 0 0-160 0 NaN > </path>"`

**Comment by elrumordelaluz** [comment]
Hi @dinoboff, thanks for open the _Issue_.

I am trying but can't reproduce. This is the result I get: `d="M336 208v-95a80 80 0 00-160 0v95"`

<img width="1153" alt="Screenshot 2020-10-12 at 12 30 25" src="https://user-images.githubusercontent.com/784056/95736695-d85c2300-0c86-11eb-87bb-a992b7df6d4c.png">
