### ISSUE TITLE
icon position trough position value instead of id.

### ISSUE THREAD

**Issue by aldaw** [elrumordelaluz/svgsprit.es#18]
I am using a addon for my forum to use .svg sprites for node icons.
But I can not use IDs instead he wants the position by value i guess viewbox like 0 0 32 32 (next icon would be i guess 32 0 32 32).

When i try using your svg sprite, it doens't seem to work, looking further into the svg file i noticed the viewboxes are all the same and the icons are only separated by id?
Is there an option for a standard svg sprite without ids?

**Comment by elrumordelaluz** [comment]
Can you expand a little more regarding your _Add-on_?

Using [svgsprit.es](https://svgsprit.es/) we create a _sprite_ but to use in the `svg` way and not in the way used by aking a `png` sprite, where using `css` we show a part of the image.

Here are [some](https://css-tricks.com/svg-sprites-use-better-icon-fonts/) [links](https://24ways.org/2014/an-overview-of-svg-sprite-creation-techniques/) explaining this technique. 

Let me know in any case,

**Comment by aldaw** [comment]
"Can you expand a little more regarding your Add-on?"
How do you mean that? :) Like implementing a compatibility for IDs? :)
Sadly i am not the coder, but I asked him already first.
I have used before a vector program to arange them by kinda hand, and said i should use old svg I used.
He kinda didn't liked yours or have time to implement the compatibilitys with IDs.

Is there no way to kinda transform it?
I forwarded a link to here to the coder will see what he says to your links :)

**Comment by elrumordelaluz** [comment]
Closing but feel free to re-open in any case.
