### ISSUE TITLE
svgs get broken

### ISSUE THREAD

**Issue by aldaw** [elrumordelaluz/svgsprit.es#22]
https://codepen.io/pen/?&editors=1100

the inner part of the logo (Cardano) kinda gets pasted into the other circles oO really strange behaviour.

Ass attachement i have the .svgs which i tried.

[CC&Forum-Icons-Svg.zip](https://github.com/elrumordelaluz/svgsprit.es/files/5937366/CC.Forum-Icons-Svg.zip)

**Comment by elrumordelaluz** [comment]
hi @aldaw the pen seems empty

**Comment by elrumordelaluz** [comment]
[Here](https://codepen.io/elrumordelaluz/pen/VwmmezV?editors=1000) is a pen created with your icons but don't know where is the issue.

**Comment by elrumordelaluz** [comment]
Closing but feel free to re-open in any case.
