### ISSUE TITLE
Messes id's and titles up

### ISSUE THREAD

**Issue by Zillion01** [elrumordelaluz/svgsprit.es#35]
Hi! 

When I try to generate a spritemap on your site it messes the id's and titles up. See attachment for the svg's I use. Half way all id's and titles and codes are in the wrong order. thanks

[Archief.zip](https://github.com/elrumordelaluz/svgsprit.es/files/6710583/Archief.zip)

**Comment by Zillion01** [comment]
Generated file (see for example the end of the file).

`<svg width="0" height="0" class="hidden">
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 30 30" id="YouTube">
        <title>YouTube</title>
        <path d="M14.887 0c8.209 0 14.887 6.678 14.887 14.887s-6.678 14.887-14.887 14.887C6.679 29.774 0 23.096 0 14.887S6.679 0 14.887 0zm5.09 8.806h-9.915a3.823 3.823 0 00-3.823 3.823v4.648a3.823 3.823 0 003.823 3.823h9.915a3.823 3.823 0 003.823-3.823v-4.648a3.823 3.823 0 00-3.823-3.823zm-6.382 3.647l3.982 2.283c.175.1.146.355-.033.451l-3.955 2.17c-.17.092-.325-.032-.325-.228v-4.452c0-.198.16-.322.33-.224z" fill-rule="evenodd"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 24" id="x">
        <title>x</title>
        <defs>
            <path d="M5.293 5.293a1 1 0 011.414 0L12 10.585l5.293-5.292a1 1 0 011.32-.083l.094.083a1 1 0 010 1.414L13.415 12l5.292 5.293a1 1 0 01.083 1.32l-.083.094a1 1 0 01-1.414 0L12 13.415l-5.293 5.292a1 1 0 01-1.32.083l-.094-.083a1 1 0 010-1.414L10.585 12 5.293 6.707a1 1 0 01-.083-1.32z" id="a"></path>
        </defs>
        <g fill="none" fill-rule="evenodd">
            <mask id="b" fill="#fff">
                <use xlink:href="#a"></use>
            </mask>
            <use fill="#000" fill-rule="nonzero" xlink:href="#a"></use>
            <g mask="url(#b)" fill="#000">
                <path d="M0 0h24v24H0z"></path>
            </g>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 30 30" id="Instagram">
        <title>Instagram</title>
        <path d="M22.431 18.37a3.851 3.851 0 01-3.85 3.851h-7.402a3.851 3.851 0 01-3.85-3.85v-7.402a3.851 3.851 0 013.85-3.85h7.401a3.851 3.851 0 013.851 3.85v7.401zm1.757-7.4a5.607 5.607 0 00-5.608-5.608h-7.4a5.607 5.607 0 00-5.608 5.607v7.401a5.607 5.607 0 005.607 5.608h7.401a5.608 5.608 0 005.608-5.608v-7.4zm-9.277 6.765a2.948 2.948 0 01-2.944-2.945 2.948 2.948 0 012.944-2.945 2.948 2.948 0 012.945 2.945 2.948 2.948 0 01-2.945 2.945zm0-7.543a4.603 4.603 0 00-4.597 4.598 4.603 4.603 0 004.597 4.597 4.603 4.603 0 004.598-4.597 4.603 4.603 0 00-4.598-4.598zm4.866-1.403a1.094 1.094 0 100 2.19 1.094 1.094 0 000-2.19zM0 14.79C0 6.635 6.635 0 14.79 0s14.79 6.635 14.79 14.79-6.635 14.79-14.79 14.79S0 22.944 0 14.79z" fill-rule="evenodd"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_visibility_off">
        <title>ic_visibility_off</title>
        <g stroke="#000" stroke-width="2" fill="none" fill-rule="evenodd" stroke-linecap="square" stroke-linejoin="round">
            <path d="M12 4c4.838 0 8.873 3.436 9.8 8-.927 4.565-4.962 8-9.8 8-4.838 0-8.873-3.435-9.8-7.999C3.127 7.436 7.162 4 12 4z"></path>
            <circle cx="12" cy="12" r="3"></circle>
            <path d="M3 21L21 3"></path>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_visibility">
        <title>ic_visibility</title>
        <g transform="translate(2 4)" stroke="#000" stroke-width="2" fill="none" fill-rule="evenodd" stroke-linecap="round" stroke-linejoin="round">
            <path d="M10 0c4.838 0 8.873 3.436 9.8 8-.927 4.565-4.962 8-9.8 8-4.838 0-8.873-3.435-9.8-7.999C1.127 3.436 5.162 0 10 0z"></path>
            <circle cx="10" cy="8" r="3"></circle>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_video full screen">
        <title>ic_video full screen</title>
        <g fill="none" fill-rule="evenodd" stroke="#000" stroke-width="2">
            <path stroke-linecap="square" d="M7 8h10v8H7z"></path>
            <path d="M10.062 3.998h-7v5m7 11h-7v-5m11-11h7v5m-7 11h7v-5"></path>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_video exit full screen">
        <title>ic_video exit full screen</title>
        <g fill="none" fill-rule="evenodd" stroke="#000" stroke-width="2">
            <path d="M3 4h18v16H3z" stroke-linecap="square"></path>
            <path d="M11 7.998H7.062v3m3.938 5H7.062v-3m6-5H17v3m-3.938 5H17v-3"></path>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_video">
        <title>ic_video</title>
        <path d="M22 5v14H8v-4.429L2 18V6l6 3.428V5h14z" stroke="#000" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="bevel"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_username">
        <title>ic_username</title>
        <g transform="translate(4 4)" stroke="#000" stroke-width="2" fill="none" fill-rule="evenodd" stroke-linejoin="round">
            <circle stroke-linecap="round" cx="8" cy="4" r="4"></circle>
            <path d="M16 16a8 8 0 10-16 0" stroke-linecap="square"></path>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_upward">
        <title>ic_upward</title>
        <path d="M12 20V5m0-1l8.062 8.062M12 4l-8.062 8.062" stroke="#000" stroke-width="2" fill="none" stroke-linecap="square"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_up">
        <title>ic_up</title>
        <path d="M20 16l-8-8m0 0l-8 8" stroke="#000" stroke-width="2" fill="none" stroke-linecap="square"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_timer">
        <title>ic_timer</title>
        <g transform="translate(2 2)" stroke="#000" stroke-width="2" fill="none" fill-rule="evenodd" stroke-linejoin="round">
            <circle stroke-linecap="round" cx="10" cy="10" r="10"></circle>
            <path d="M10 4v6l-2 4" stroke-linecap="square"></path>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_time">
        <title>ic_time</title>
        <path d="M2 2h20M2 22h20M4 2a8 8 0 008 8h0a8 8 0 008-8M4 22a8 8 0 018-8h0a8 8 0 018 8" stroke="#000" stroke-width="2" fill="none" stroke-linecap="square" stroke-linejoin="round"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_tick">
        <title>ic_tick</title>
        <path d="M3 12l6 6m0 0L21 6" stroke="#000" stroke-width="2" fill="none" stroke-linecap="square"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_swipe">
        <title>ic_swipe</title>
        <g fill="#FFF" fill-rule="evenodd" stroke-linecap="round" stroke="#000" stroke-width="2">
            <path d="M7.283 8L5 16.523l11 2.947V22H2V8h5.283z"></path>
            <path d="M8.623 3l13.523 3.623-3.623 13.523L5 16.523z"></path>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_sound on">
        <title>ic_sound on</title>
        <g fill="none" fill-rule="evenodd" stroke="#000" stroke-width="2">
            <path d="M18 11l-2-2m0 5.464l2.737-2.736" stroke-linecap="square"></path>
            <path d="M6 9H2v6h4l5 4V5z"></path>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_sound off">
        <title>ic_sound off</title>
        <g fill="none" fill-rule="evenodd" stroke="#000" stroke-width="2">
            <path d="M21.464 14.464L16 9m0 5.464L21.464 9" stroke-linecap="square"></path>
            <path d="M6 9H2v6h4l5 4V5z"></path>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_slash forward">
        <title>ic_slash forward</title>
        <path d="M19 5L6 18" stroke="#000" stroke-width="2" fill="none" stroke-linecap="square"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_slash backward">
        <title>ic_slash backward</title>
        <path d="M6 5l13 13" stroke="#000" stroke-width="2" fill="none" stroke-linecap="square"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_share">
        <title>ic_share</title>
        <g transform="translate(4 3)" stroke="#000" stroke-width="2" fill="none" fill-rule="evenodd" stroke-linejoin="round">
            <circle stroke-linecap="round" cx="13" cy="3" r="3"></circle>
            <circle stroke-linecap="round" cx="3" cy="10" r="3"></circle>
            <circle stroke-linecap="round" cx="13" cy="16" r="3"></circle>
            <path stroke-linecap="square" d="M6 8l4-3m-4 7l4 2"></path>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_settings">
        <title>ic_settings</title>
        <g fill="none" fill-rule="evenodd" stroke-linecap="square" stroke="#000" stroke-width="2">
            <circle cx="12" cy="12" r="3"></circle>
            <circle cx="12" cy="12" r="8"></circle>
            <path d="M12 4V2m0 20v-2M6.343 6.343L4.93 4.928M19.071 19.07l-1.414-1.414M4 12H2m20 0h-2M6.343 17.657L4.93 19.072M19.071 4.93l-1.414 1.414"></path>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_send">
        <title>ic_search</title>
        <g stroke="#000" stroke-width="2" fill="none" fill-rule="evenodd" stroke-linecap="square">
            <circle cx="11" cy="11" r="7"></circle>
            <path d="M20 20l-3.536-3.536"></path>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_search">
        <title>ic_send</title>
        <path stroke="#000" stroke-width="2" d="M4 3l17 9-17 9 5-9z" fill="none" stroke-linecap="round" stroke-linejoin="bevel"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_rotate_clockwise">
        <title>ic_rotate_clockwise</title>
        <g stroke="#000" fill="none" fill-rule="evenodd">
            <path d="M16.72 17.593A8 8 0 1111 4h0a8 8 0 018 8" stroke-width="2" stroke-linejoin="round"></path>
            <path fill="#000" stroke-linecap="round" d="M16 11h6l-3 4z"></path>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_rewind">
        <title>ic_rewind</title>
        <g stroke="#000" fill="none" fill-rule="evenodd">
            <path d="M16.72 6.407A8 8 0 1011 20h0a8 8 0 008-8" stroke-width="2"></path>
            <path fill="#000" stroke-linecap="round" d="M16 13h6l-3-4z"></path>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_profile_info">
        <title>ic_profile_info</title>
        <g stroke="#000" stroke-width="2" fill="none" fill-rule="evenodd" stroke-linecap="square">
            <path d="M1 2h7l2 2h13v18h-7l-2-2H1z"></path>
            <circle cx="9" cy="10" r="2"></circle>
            <path d="M13 16a4 4 0 10-8 0m12-6h2m-2 4h2"></path>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_print">
        <title>ic_print</title>
        <g fill="none" fill-rule="evenodd" stroke-linecap="square" stroke="#000" stroke-width="2">
            <path d="M9 13h6v9H9zm-2 0h10"></path>
            <path d="M9 18H3V7h18v11h-6M7 3h10v4H7z"></path>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_pointer down">
        <title>ic_pointer down</title>
        <path d="M19 11v8h-8m7-1L5 5" stroke="#000" stroke-width="2" fill="none" stroke-linecap="square"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_pointer">
        <title>ic_pointer</title>
        <path d="M11 5h8v8m-1-7L5 19" stroke="#000" stroke-width="2" fill="none" stroke-linecap="square"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_plus">
        <title>ic_plus</title>
        <path d="M12 3v18m-9-9h18" stroke="#000" stroke-width="2" fill="none" stroke-linecap="square"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_play">
        <title>ic_play</title>
        <g fill="none" fill-rule="evenodd">
            <circle stroke="#000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" cx="12" cy="12" r="10"></circle>
            <path fill="#000" d="M10 17V7l6 5z"></path>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_pauze">
        <title>ic_pauze</title>
        <g fill="none" fill-rule="evenodd" stroke="#000" stroke-width="2">
            <circle stroke-linecap="round" stroke-linejoin="round" cx="12" cy="12" r="10"></circle>
            <path stroke-linecap="square" d="M10 16V8m4 8V8"></path>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_password">
        <title>ic_password</title>
        <path d="M4 8h16v12H4zm6 6h4M8 4h8v4H8z" fill="none" stroke-linecap="square" stroke="#000" stroke-width="2"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_notification">
        <title>ic_notification</title>
        <g stroke="#000" stroke-width="2" fill="none" fill-rule="evenodd">
            <path d="M12 5a6 6 0 016 6h0v7H6v-7l.004-.225A6 6 0 0112 5zM9 18a3 3 0 006 0H9z" stroke-linecap="round"></path>
            <path stroke-linecap="square" d="M12 5V3"></path>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_next">
        <title>ic_next</title>
        <path d="M4 12h15m1 0l-8.062-8.062M20 12l-8.062 8.062" stroke="#000" stroke-width="2" fill="none" stroke-linecap="square"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_minus">
        <title>ic_minus</title>
        <path d="M3 12h18" stroke="#000" stroke-width="2" fill="none" stroke-linecap="square"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_message">
        <title>ic_message</title>
        <g transform="translate(3 3)" fill="none" fill-rule="evenodd">
            <path stroke="#000" stroke-width="2" stroke-linecap="round" d="M0 0h18v13H8l-8 5z"></path>
            <circle fill="#000" cx="5" cy="7" r="1"></circle>
            <circle fill="#000" cx="9" cy="7" r="1"></circle>
            <circle fill="#000" cx="13" cy="7" r="1"></circle>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_menu">
        <title>ic_menu</title>
        <path d="M3 12h16M3 6h16M3 18h16" fill="none" stroke-linecap="square" stroke="#000" stroke-width="2"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_location">
        <title>ic_location</title>
        <g transform="rotate(45 2.964 15.743)" stroke="#000" stroke-width="2" fill="none" fill-rule="evenodd">
            <path d="M6 0a6 6 0 016 6h0v6H6A6 6 0 116 0z" stroke-linecap="round"></path>
            <circle cx="6" cy="6" r="2"></circle>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_list">
        <title>ic_list</title>
        <path d="M2 2h4v4H2zm0 8h4v4H2zm0 8h4v4H2zm8-16h12v4H10zm0 8h12v4H10zm0 8h12v4H10z" fill-rule="evenodd"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_info">
        <title>ic_home</title>
        <path d="M2 12l10-8m0 0l10 8M6 15v6m12-6v6" stroke="#000" stroke-width="2" fill="none" stroke-linecap="square" stroke-linejoin="round"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_home">
        <title>ic_grid</title>
        <path d="M2 2h4v4H2zm0 8h4v4H2zm0 8h4v4H2zm8-16h4v4h-4zm0 8h4v4h-4zm0 8h4v4h-4zm8-16h4v4h-4zm0 8h4v4h-4zm0 8h4v4h-4z" fill-rule="evenodd"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_heart">
        <title>ic_info</title>
        <g fill="none" fill-rule="evenodd">
            <circle stroke="#000" stroke-width="2" cx="12" cy="12" r="9"></circle>
            <path fill="#000" d="M11 10h2v7h-2z"></path>
            <rect fill="#000" x="11" y="7" width="2" height="2" rx="1"></rect>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_grid">
        <title>ic_heart</title>
        <path d="M20.728 13.243l-8.485 8.485-8.486-8.485a6 6 0 018.486-8.486 6 6 0 018.485 8.486z" stroke="#000" stroke-width="2" fill="none" stroke-linecap="round"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_goals">
        <title>ic_goals</title>
        <g transform="translate(4 4)" stroke="#000" stroke-width="2" fill="none" fill-rule="evenodd">
            <circle stroke-linecap="round" stroke-linejoin="round" cx="6.5" cy="10.5" r="6.5"></circle>
            <path stroke-linecap="square" d="M13 0h4v4"></path>
            <path stroke-linecap="square" stroke-linejoin="round" d="M16 1L6 11"></path>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_gallery">
        <title>ic_filter</title>
        <g transform="rotate(90 8.5 11.5)" stroke="#000" fill="none" fill-rule="evenodd">
            <path stroke-width="2" stroke-linecap="square" d="M9 0v16m7-16v16M2 0v16"></path>
            <circle fill="#000" stroke-linecap="round" cx="2" cy="4" r="2"></circle>
            <circle fill="#000" stroke-linecap="round" cx="16" cy="4" r="2"></circle>
            <circle fill="#000" stroke-linecap="round" cx="9" cy="12" r="2"></circle>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_forward">
        <title>ic_gallery</title>
        <g fill="none" fill-rule="evenodd" stroke-linecap="round" stroke="#000" stroke-width="2">
            <path d="M4 4h16v16H4z"></path>
            <path d="M7 11l3 3 5-6 5 6v6H4v-6z"></path>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_filter">
        <title>ic_forward</title>
        <path d="M8 4l8 8m0 0l-8 8" stroke="#000" stroke-width="2" fill="none" stroke-linecap="square"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_feedback">
        <title>ic_edit</title>
        <g stroke-width="2" fill="none" fill-rule="evenodd">
            <path stroke="#0C0C0C" stroke-linecap="round" d="M16.243 3.515l4.242 4.242-9.9 9.9-4.949.707.707-4.95z"></path>
            <path stroke="#000" stroke-linecap="square" d="M13.414 6.343l4.243 4.243"></path>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_feed">
        <title>ic_feed</title>
        <path d="M3 4h18v16H3zm4 6h10.05M9 14h6" stroke="#000" stroke-width="2" fill="none" stroke-linecap="square"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_edit">
        <title>ic_dropdown_cyan</title>
        <path d="M7 8h10l-5 5z" fill-rule="evenodd"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_dropdown_cyan">
        <title>ic_feedback</title>
        <path d="M19.005 3C20.107 3 21 3.894 21 5.003v8.994A1.999 1.999 0 0119.005 16H15.75L12 21l-3.75-5H4.995A1.997 1.997 0 013 13.997V5.003C3 3.897 3.893 3 4.995 3h14.01zM8 7h8m-8 5h8" fill="none" stroke-linecap="square" stroke="#000" stroke-width="2"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_downwards">
        <title>ic_delete</title>
        <g transform="translate(2 2)" stroke="#000" stroke-width="2" fill="none" fill-rule="evenodd">
            <circle cx="10" cy="10" r="10"></circle>
            <path stroke-linecap="square" d="M5 10h10"></path>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" id="ic_download">
        <title>ic_cross arrow small</title>
        <path d="M3.757 3.757L11.3 11.3m.471.471V4.17m0 7.601H4.17" stroke="#000" fill="none" stroke-linecap="square"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_down">
        <title>ic_done</title>
        <g fill="none" fill-rule="evenodd" stroke-linecap="square" stroke="#000" stroke-width="2">
            <circle cx="12" cy="12" r="9"></circle>
            <path d="M9 13l2 2m0 0l5-5"></path>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_done">
        <title>ic_downwards</title>
        <path d="M12 3v16m0 1l-8.062-8.062M12 20l8.062-8.062" stroke="#000" stroke-width="2" fill="none" stroke-linecap="square"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_delete">
        <title>ic_down</title>
        <path d="M4 8l8 8m0 0l8-8" stroke="#000" stroke-width="2" fill="none" stroke-linecap="square"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_cross arrow small">
        <title>ic_download</title>
        <path stroke="#000" stroke-width="2" stroke-linecap="square" d="M16.243 12.243L12 16.485l-4.243-4.242M12 15.728V3M3 21v-3m18 3v-3M3 21h18" fill="none"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_cancel">
        <title>ic_cancel</title>
        <path d="M5 5l14.142 14.142M19 5L5 19" fill="none" stroke-linecap="square" stroke="#000" stroke-width="2"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_camera">
        <title>ic_bookmark</title>
        <path d="M5 2h14v20l-7-4-7 4z" stroke="#000" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="bevel"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_calender">
        <title>ic_attachment</title>
        <g fill="none" fill-rule="evenodd" stroke="#000" stroke-width="2">
            <path d="M19 8c0-3.866-2.91-7-6.5-7S6 4.134 6 8m0 0v10"></path>
            <path d="M6 18a4.5 4.5 0 004.5 4.5h0A4.5 4.5 0 0015 18" stroke-linecap="square"></path>
            <path d="M15 18V8m0 0a2.5 2.5 0 10-5 0m0 0v9m9-9v9"></path>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 32" id="ic_bookmark">
        <title>ic_arrow long up</title>
        <path d="M13 31V4.83l9.293 9.291 1.414-1.414L13 2.001V2h-.001L12 1l-1 1v.001L.293 12.707l1.414 1.414L11 4.83V31h2z"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_back">
        <title>ic_camera</title>
        <g transform="translate(2 4)" stroke="#000" stroke-width="2" fill="none" fill-rule="evenodd">
            <path stroke-linecap="round" d="M0 3h20v14H0z"></path>
            <circle cx="13" cy="10" r="3"></circle>
            <path fill="#000" stroke-linecap="round" d="M2 0h6v3H2z"></path>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 32" id="ic_attachment">
        <title>ic_arrow long down</title>
        <path d="M11 1v26.17l-9.293-9.291-1.414 1.414L11 29.999V30h.001L12 31l1-1v-.001l10.707-10.706-1.414-1.414L13 27.17V1h-2z"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 25" id="ic_arrow long up">
        <title>ic_back</title>
        <path d="M20 13H5m-1 0l8.062-8.062M4 13l8.062 8.062" stroke="#000" stroke-width="2" fill="none" stroke-linecap="square"></path>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="ic_arrow long down">
        <title>ic_calender</title>
        <g fill="none" fill-rule="evenodd">
            <path stroke="#000" stroke-width="2" stroke-linecap="square" d="M3 7h18v14H3zm5 2V4m8 5V4"></path>
            <circle fill="#000" cx="8" cy="13" r="1"></circle>
            <circle fill="#000" cx="8" cy="17" r="1"></circle>
            <circle fill="#000" cx="12" cy="13" r="1"></circle>
            <circle fill="#000" cx="12" cy="17" r="1"></circle>
            <circle fill="#000" cx="16" cy="13" r="1"></circle>
            <circle fill="#000" cx="16" cy="17" r="1"></circle>
        </g>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 30 30" id="ic_alerts">
        <title>Facebook</title>
        <path d="M14.887 0c8.209 0 14.887 6.679 14.887 14.887 0 8.209-6.678 14.887-14.887 14.887C6.68 29.774 0 23.096 0 14.887 0 6.68 6.679 0 14.887 0zm3.904 5.964h-3.025a3.214 3.214 0 00-3.213 3.214v2.547H10.95a.225.225 0 00-.225.225v2.642c0 .124.1.225.225.225h1.602v8.768c0 .125.1.225.224.225h3.204c.124 0 .225-.1.225-.225v-8.768h2.323c.117 0 .214-.09.224-.206l.223-2.642a.225.225 0 00-.224-.244h-2.546V9.851c0-.44.356-.796.796-.796h1.79c.124 0 .224-.1.224-.224V6.189c0-.125-.1-.225-.225-.225z" fill-rule="evenodd"></path>
    </symbol>
</svg>`

**Comment by elrumordelaluz** [comment]
Hi @Zillion01, thanks for open the _Issue_.
Could you please tell which _browser_ are you using?

I am using Firefox and downloading your `.zip` file am getting [this result](https://codepen.io/elrumordelaluz/pen/rNmxmjM?editors=1000) which seems ok (let me know if it is wrong).

**Comment by Zillion01** [comment]
I used Chrome on your site. Latest and latest MacOS. I gave up tho don't use the sprite map in my current project.

**Comment by elrumordelaluz** [comment]
No problem @Zillion01 I'm closing the _issue_. However feel free to re-open in any case.

ps/ Just a curiosity, is the result shared [here](https://github.com/elrumordelaluz/svgsprit.es/issues/35#issuecomment-874225324) seems correct for you?

**Comment by Zillion01** [comment]
Sry I overlooked  your link. Yes this seems to be correct. What caused the mess? Next project I am happy to use your work again. thanks

**Comment by elrumordelaluz** [comment]
In fact, I am curious on the result I obtained to debug a little more. Thanks again.
