### ISSUE TITLE
Some elements lose their color

### ISSUE THREAD

**Issue by Lucile-Besse** [elrumordelaluz/svgsprit.es#36]
I try to create a sprite with multiple svg and some svg lose their colors.
In the screenshot below, you can see on the right the original svg and on the left the "sprited" svg : 
![color-issue](https://user-images.githubusercontent.com/60396192/124898205-43047a00-dfdf-11eb-91e3-a44f23828646.jpg)
AS you can see the head should be green.

**Comment by elrumordelaluz** [comment]
Hi @Lucile-Besse, thanks for open the _Issue_.

Could you please share the `svg`, in order to analyze why this happens?

**Comment by Lucile-Besse** [comment]
Yes for sure,

SVG attached file : original file.
Html attached file : the demo from https://svgsprit.es/

Lucile

De : Lionel ***@***.***>
Envoyé : jeudi 8 juillet 2021 14:47
À : elrumordelaluz/svgsprit.es ***@***.***>
Cc : Lucile Besnard ***@***.***>; Mention ***@***.***>
Objet : Re: [elrumordelaluz/svgsprit.es] Some elements lose their color (#36)


Hi @Lucile-Besse<https://github.com/Lucile-Besse>, thanks for open the Issue.

Could you please share the svg, in order to analyze why this happens?

**Comment by elrumordelaluz** [comment]
In case you included the file/s I can't see or missing something.

**Comment by elrumordelaluz** [comment]
Closing but feel free to re-open in any case.
