### ISSUE TITLE
Not able to ungroup

### ISSUE THREAD

**Issue by meetdilip** [elrumordelaluz/svgsprit.es#4]
Hi, I made an SVG sprite using https://svgsprit.es/

Everything went well. But when I drop it as a `symbol` inside Inkscape, I am not able to ungroup the SVG. I can change the colours as a whole. But not separate the objects and then colour them individually. It will be great if you can suggest a workaround. Thanks.

**Comment by elrumordelaluz** [comment]
Closing but feel free to re-open in any case.
