### ISSUE TITLE
Terrible update

### ISSUE THREAD

**Issue by epicbytes** [elrumordelaluz/svgsprit.es#57]
<img width="1541" alt="image" src="https://github.com/elrumordelaluz/svgsprit.es/assets/5072946/a6d74d6b-c882-4f1f-95a6-c63ad98c064b">

Please bring back the old site, the current one is unusable!

**Comment by elrumordelaluz** [comment]
Sorry for that @epicbytes. The patch should be available in minutes. 
Thank you for pointing this out!
