### ISSUE TITLE
xlink:href is deprecated in SVG2

### ISSUE THREAD

**Issue by anuraagvaidya** [elrumordelaluz/svgsprit.es#7]
Hey there,

Thanks for creating this awesome tool.
Just wanted to bring to your notice that `xlink:href` attribute has been deprecated.

Please [refer this](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href)
I was creating my SVG tag dynamically, and the browser wasn't loading the SVG sprites. When I removed xlink: from them it started working.

**Comment by elrumordelaluz** [comment]
Hi @anuraagvaidya, thanks for open the _Issue_.

Cool! mind making a PR to fix that? 
Thanks in advance.
