### ISSUE TITLE
Gradient ID

### ISSUE THREAD

**Issue by buzzclue** [elrumordelaluz/svgsprit.es#9]
Hi There,

This is by far my most favorite generator. 

If you have sprites with gradients fill then the generator converts the ID's and name all of them "a" which works in Firefox but not in Chrome.

Firefox Preview which shows correct gradient.
![image](https://user-images.githubusercontent.com/43321373/84507500-5b21a100-acda-11ea-978f-e0990054c72f.png)

Chrome Preview of same File.
![image](https://user-images.githubusercontent.com/43321373/84507571-78ef0600-acda-11ea-85b6-0a8cc478b743.png)

Now if I manually change the ID's Chrome works fine.

**Comment by elrumordelaluz** [comment]
Hi @buzzclue, thanks for open the _Issue_.

I am sorry for the delay. Do you have the Icons you used in order to debug the _issue_ with them?

Thank!

**Comment by buzzclue** [comment]
Here are some SVG's with gradient, You can try generate sprite with them and test cross browser. 

![image](https://user-images.githubusercontent.com/43321373/95765654-a0c39a00-0ccb-11eb-8289-e9c0b040c672.png)
![image](https://user-images.githubusercontent.com/43321373/95765691-aa4d0200-0ccb-11eb-8d1c-ef2919e50c4d.png)
![image](https://user-images.githubusercontent.com/43321373/95765716-afaa4c80-0ccb-11eb-8d3e-38020c29a1ac.png)
